---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "uname" . }}-config
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "uname" . }}"
data:
{{- if .Values.settings.node }}
  elasticsearch.yml: |
{{ toYaml .Values.settings.node | indent 4 }}
{{- end }}
{{- if .Values.esConfig }}
{{- range $path, $config := .Values.esConfig }}
  {{ $path }}: |
{{ $config | indent 4 -}}
{{- end -}}
{{- end -}}
